### ISSUE TITLE
Given 2captcha key null is invalid

### ISSUE THREAD

**Issue by redking974** [drallieiv/KinanCity#13]
Hello, in the wiki (https://github.com/drallieiv/KinanCity/blob/develop/KinanCity-core/README.md) it's written for Kinan that ck is optional. But if I don't enter it, I got an error :
I've try with value empty into the config, and without the config file.

My command line :
```
@echo off

java -jar KinanCity-core-1.2.0-SNAPSHOT.jar -m XXX@XXX.fr -f XXX**** -p YYY -c 5 -s 1

echo "KinanCity execution stopped"
pause
```

My log :
```
INFO  [Kinan City]  -- Start Kinan City CLI --
WARN  [Kinan City] Skipping loading configuration file, you may copy config.example.properties as config.properties and edit your configuration
INFO  [Kinan City] Use a Sequence Account Generator
ERROR [Kinan City] Configuration Init Failed
com.kinancity.core.errors.ConfigurationException: com.kinancity.api.errors.TwoCaptchaConfigurationException: Given 2captcha key null is invalid
        at com.kinancity.core.Configuration.init(Configuration.java:87)
        at com.kinancity.core.Configuration.checkConfiguration(Configuration.java:117)
        at com.kinancity.core.KinanCityCli.main(KinanCityCli.java:40)
Caused by: com.kinancity.api.errors.TwoCaptchaConfigurationException: Given 2captcha key null is invalid
        at com.kinancity.api.captcha.TwoCaptchaService.getBalance(TwoCaptchaService.java:127)
        at com.kinancity.api.captcha.TwoCaptchaService.<init>(TwoCaptchaService.java:101)
        at com.kinancity.core.Configuration.init(Configuration.java:85)
        ... 2 common frames omitted
ERROR [Kinan City] Account creation failed, missing configuration
"KinanCity execution stopped"
Appuyez sur une touche pour continuer...
```

**Comment by drallieiv** [comment]
As the log says 

> you may copy config.example.properties as config.properties and edit your configuration

or you can set your key at each run with `-ck` or `-captchaKey`

**Comment by redking974** [comment]
Thanks for reply. But in the wiki -ck is reported as "Additional parameters". Is it a mandatory parameter ?
Regards

**Comment by drallieiv** [comment]
It is optional only if you already have one in your config file.
If given twice, the command line one precedes.

**Comment by redking974** [comment]
Sorry, it was a misunderstood from my part. I believe it was optionnal and that we could use it without apikey (manually via ChromeDriver). Regards.
