### ISSUE TITLE
JsonParsingException with 2captcha when checking balance

### ISSUE THREAD

**Issue by tolukolvi** [drallieiv/KinanCity#26]
INFO  [Kinan City]  -- Start Kinan City CLI --
INFO  [Kinan City] ProxyManager setup with 7 proxies
INFO  [Kinan City] Create a single account
Exception in thread "Kinan City" javax.json.stream.JsonParsingException: Unexpected char 60 at (line no=1, column no=1, offset=0)
        at org.glassfish.json.JsonTokenizer.unexpectedChar(JsonTokenizer.java:532)
        at org.glassfish.json.JsonTokenizer.nextToken(JsonTokenizer.java:415)
        at org.glassfish.json.JsonParserImpl$NoneContext.getNextEvent(JsonParserImpl.java:222)
        at org.glassfish.json.JsonParserImpl$StateIterator.next(JsonParserImpl.java:172)
        at org.glassfish.json.JsonParserImpl.next(JsonParserImpl.java:149)
        at org.glassfish.json.JsonReaderImpl.readObject(JsonReaderImpl.java:101)
        at com.kinancity.core.captcha.twoCaptcha.TwoCaptchaProvider.getBalance(TwoCaptchaProvider.java:266)
        at com.kinancity.core.Configuration.init(Configuration.java:98)
        at com.kinancity.core.Configuration.checkConfiguration(Configuration.java:155)
        at com.kinancity.core.KinanCityCli.main(KinanCityCli.java:40)

![kinan_error](https://cloud.githubusercontent.com/assets/22489426/25740962/687c16ae-3191-11e7-8deb-44e546d86577.png)

**Comment by drallieiv** [comment]
Additional logs added by 5320106 should help

@tolukolvi could you retry with same configuration ?

**Comment by tolukolvi** [comment]
Now I'm getting this with the same config and startup parameters.

![kinan_error2](https://cloud.githubusercontent.com/assets/22489426/25760863/685636a0-31e1-11e7-896c-962a7e79dfef.png)

**Comment by drallieiv** [comment]
Seen in DM, here was using some kind of antivirus/live protection that was blocking access to the web pages.
